# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

[[main]]
  name = "About"
  url = "#about"
  weight = 10

[[main]]
  name = "Projects"
  url = "#projects"
  weight = 30

[[main]]
  name = "Experience"
  url = "#experience"
  weight = 40

[[main]]
  name = "Talks"
  url = "#talks"
  weight = 50

[[main]]
  name = "Coursework"
  url = "#courses"
  weight = 60

[[main]]
  name = "Resume"
  url = "files/GabriellaNovak_Resume.pdf"
  weight = 70

[[main]]
  name = "Hobbies & Interests"
  url = "#hobby"
  weight = 80

[[main]]
  name = "Contact"
  url = "#contact"
  weight = 90
